apply plugin: 'maven-publish'

publishing {
    repositories {
        maven {
            if (System.env.RELEASE_TYPE == "beta" || System.env.RELEASE_TYPE == "stable") {
                url System.env.REPO_PATH_GITLAB_REGISTRY
                credentials(HttpHeaderCredentials) {
                    name = "Deploy-Token"
                    value = System.env.GITLAB_DEPLOY_TOKEN
                }
                authentication {
                    header(HttpHeaderAuthentication)
                }
            } else {
                url mavenLocal().url
            }
        }
    }
    publications {
        release(MavenPublication) {
            groupId = "com.drivequant.drivekit"
            artifactId = project.artifactId
            version = android.defaultConfig.versionName
            
            afterEvaluate {
                from components.release
            }
        }
    }
}
