pluginManagement {
    repositories {
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://maven.drivequant.com/repository/android-sdk/"
        }
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "https://gitlab.com/api/v4/projects/84225187/packages/maven"
        }
    }
}

include ':app',
        ':DriverDataUI',
        ':DriverAchievementUI',
        ':CommonUI',
        ':VehicleUI',
        ':PermissionsUtilsUI',
        ':ChallengeUI',
        ':TripAnalysisUI',
        ':DriverDataTimelineUI'
